name: Conditional, Sharing and Matrix Workflow Example

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Create hello.txt
      run: echo "Hello, GitHub Actions!" > hello.txt

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact-${{ matrix.os }} 
        path: hello.txt

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: my-artifact-ubuntu-latest

    - name: List files
      run: ls -la

    - name: Check current directory
      run: pwd

    - name: Display hello.txt
      run: cat hello.txt
